CREATE TABLE QUOTE
(
  ID NUMBER NOT NULL,
  TEXT VARCHAR2(4096) NOT NULL,
  SOURCE VARCHAR2(256),
  SOURCE_TYPE VARCHAR2(16),
  YEAR VARCHAR2(32),
  AUTHOR_ID NUMBER NOT NULL,
  CATEGORY_ID NUMBER NOT NULL
);

CREATE SEQUENCE quotes_quote_id_seq;

CREATE TABLE AUTHOR
(
  ID NUMBER NOT NULL,
  FULL_NAME VARCHAR2(128) NOT NULL,
  IMAGE_NAME VARCHAR (64)
);

CREATE SEQUENCE quotes_author_id_seq;

CREATE TABLE CATEGORY
(
  ID NUMBER NOT NULL,
  NAME VARCHAR2(128) NOT NULL,
  IMAGE_NAME VARCHAR (32)
);

CREATE SEQUENCE quotes_category_id_seq;